# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 889fea792c12662e8a52336e21c7e5ef40e15f69450002101268308521af0093825e37953a828d0024548a6741f42c5bb1c3bc22005d867f8ef1fc1782951d56

test:
  secret_key_base: 23732090f9080522398b72c895afa1c3701aee65f37ca9dea6c1556c773d5ed550c7afbffd25a05a5b6ab8de2c62579859d0a63f9ea9ca8abed06f6fa6f3546a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
